<a href="https://colab.research.google.com/github/Vinay-Kumar03/Pandas-Notes/blob/main/Vinay_Pandas_Notes_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PANDAS :
--> open source library mainly works with Realtional or Labeled Database

why we are using pandas?

--> fast,high prformance and productive

--> it is more advanced than advanced excel

who developed pandas ?

--> Mc Kinney --> 2008(in market)

what is the functions of pandas?

--> Analysing,Cleaning,Exploring and Manipulating the data

In [ ]:
#what is Data Cleaning?
#delete irrelevant rows, wrong values,empty or null values and correction of data types,delete duplicates...etc

In [ ]:
#why we are using pandas?
""" 1 . Fast and efficient data manipulation  and analysing
    2 . Easy to load the data
    3 . Easy to insert and delete the columns
    4 . Flexible reshaping and pivoting the data sets
    5 . Time series analysis and Functionality
    6 . Data visualization
    7 . Split-apply(methods)-combine operations
    8 . Group by functionality """

' 1 . Fast and efficient data manipulation  and analysing\n    2 . Easy to load the data\n    3 . Easy to insert and delete the columns\n    4 . Flexible reshaping and pivoting the data sets\n    5 . Time series analysis and Functionality\n    6 . Data visualization\n    7 . Split-apply(methods)-combine operations\n    8 . Group by functionality '

# Installation of pandas

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
#what is pip?
#pip is a python package manager
#what is library?
#it is similar to module where is having inbuilt codes present in it
#what is module?
#Module is a file where is having predefined functions and global variables

In [ ]:
import pandas as pd

In [ ]:
#how many types of data structures do we have in pandas?
# 1d--> series
# 2d--> dataframe
# 3d--> panel

# 1D--> Series
--> series are nothing but 1d labeled array which holds --> int,float,str,object

--> no columns only rows

In [ ]:
import numpy as np

In [ ]:
a= np.array([1,2,3,4])
print(a)
a.ndim #to find the dimensionality of array

[1 2 3 4]

1

In [ ]:
print(a[0])
print(a[2])

1
3

In [ ]:
sr=pd.Series(a)
sr

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#How can we change the labels
sr=pd.Series(a,index=['charan','b','c','d'])
print(sr)

charan    1
b         2
c         3
d         4
dtype: int64

In [ ]:
#create a series from the dictionary?
#we cannot replace labels from dictionary in series
d= {'name' : 'Charan','age': 22,'mobileno': 7799431776,'hobbies':'Cooking,travelling','address':'Hyderabad'}
sr=pd.Series(d,index=['a','b','c','d','e'])
print(sr)
print(type(sr))
#how can we represent series in pandas?
#<class 'pandas.core.series.Series'>

a    NaN
b    NaN
c    NaN
d    NaN
e    NaN
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
#print the dictionary with specific key values --> yes we can provide key names in the index
sr=pd.Series(d,index=['name','age'])
sr

name    Charan
age         22
dtype: object

In [ ]:
a=('apple','banana','kiwi','orange')
sr=pd.Series(a,index=['a','b','c','d'])
sr

a     apple
b    banana
c      kiwi
d    orange
dtype: object

In [ ]:
#can we create a series from set?
s=[1,2,3,4,5]   # set 'type' is unordered no label
sr=pd.Series(s)
sr
#Note : we cannot build the series from sets becoz it is unordered

0    1
1    2
2    3
3    4
4    5
dtype: int64

Series

how can we create series --> pd.series(collection_name)

how can we change labels --> pd.Series(collection_name,index=['a','b','c'...])

can we create a series from sets -->   no becoz sets are unordered

In [ ]:
#2d--> Data frame
#what is a data frame ?
# 2d-size,mutable ,heterogenous data with labeled axis(rows and columns)
#columns: it is also known as "features","Variables",'fields","dimension"
#Rows : it is also known as 'records','values','index'

In [ ]:
#applications of data frame?
# it works on data sets
#analysis
#processing
#cleaning
#join the multiple data
#create,excel,csv,json,binary files
#compute mathematical and statastical operations
#group by functions

In [ ]:
import pandas as pd

In [ ]:
#create a dataframe
data= {'name':'a','b':[1,2],'c':[11,12],'d':'apple'}
data

{'name': 'a', 'b': [1, 2], 'c': [11, 12], 'd': 'apple'}

In [ ]:
df=pd.DataFrame(data)
print(df)
print(type(df))

  name  b   c      d
0    a  1  11  apple
1    a  2  12  apple
<class 'pandas.core.frame.DataFrame'>

In [ ]:
l=[1,2,3,4,5,6,7,8]
df=pd.DataFrame(l)
df

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8

In [ ]:
#can we create a dataframe from set--->yes we can create
s={1,2,3,4,5,6,7}
s1={'apple','bananan','kiwi','mango'}
ds=pd.DataFrame(s1)
ds

         0
0    apple
1     kiwi
2  bananan
3    mango

In [ ]:
#importing and exporting the Data frames
#1 . CSV -->comma,separate,values
#read the csv file by using the pandas
df=pd.read_csv("/content/sample_data/california_housing_test.csv")
#read the content in csv i want to read first 5 rows
df.head()#df.head() read first 5 rows default
df.tail()#it reads default of last 5 rows

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
#covert or export the df in to excel file
#syntax : df.to_excel("file_name.xlsx")
df.to_excel('sample.xlsx')

In [ ]:
df=pd.read_excel("/content/sample.xlsx")
df.head()

,Unnamed: 0,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,0,-122.05,37.37,27,3885,661,1537,606,6.6085,344700
1,1,-118.30,34.26,43,1510,310,809,277,3.5990,176500
2,2,-117.81,33.78,27,3589,507,1484,495,5.7934,270500
3,3,-118.36,33.82,28,67,15,49,11,6.1359,330000
4,4,-119.67,36.33,19,1241,244,850,237,2.9375,81700

In [ ]:
df.to_json('sample.json')

# Data Frame funtions

In [ ]:
#Take any csv file
# Read the data
df=pd.read_csv("/content/sample_data/california_housing_train.csv")

In [ ]:
#check the size and index of the data frame
df.size   #size is ntg but --> no of rows * no of columns

153000

In [ ]:
#index gives the range of index start to end (start,stop,step)
df.index

RangeIndex(start=0, stop=17000, step=1)

In [ ]:
#read the columns of your df
#i want to know all columns in df
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
#how can i get the overall information of df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [ ]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

This Data set is having 17000 rows and 9 columns

There are no null values

for all the columns the data types is 'float'

In [ ]:
#print the dtype for the df
print(df.dtypes)

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

In [ ]:
#how to describe the over all data according to statastics
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [ ]:
#i want to check last 10 rows of my df
df.tail(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16990,-124.22,41.73,28.0,3003.0,699.0,1530.0,653.0,1.7038,78300.0
16991,-124.23,41.75,11.0,3159.0,616.0,1343.0,479.0,2.4805,73200.0
16992,-124.23,40.81,52.0,1112.0,209.0,544.0,172.0,3.3462,50800.0
16993,-124.23,40.54,52.0,2694.0,453.0,1152.0,435.0,3.0806,106700.0
16994,-124.25,40.28,32.0,1430.0,419.0,434.0,187.0,1.9417,76100.0
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [ ]:
#check null values in df
#df.isna
df.isna()
#returns the boolean expression if null values present then it prints "True" no null values means it prints "False"

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
16995,False,False,False,False,False,False,False,False,False
16996,False,False,False,False,False,False,False,False,False
16997,False,False,False,False,False,False,False,False,False
16998,False,False,False,False,False,False,False,False,False
16999,False,False,False,False,False,False,False,False,False

In [ ]:
#i want to know sum of null values
df.isna().sum()
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
#how can we drop the null values from df?
df.dropna()
#df.dropna(axis=0,how= any/all, thresh=None,subset=None)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

# Accesing DF

In [ ]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
df['total_bedrooms']
#read the first 5
df['total_bedrooms'].head()

0    1283.0
1    1901.0
2     174.0
3     337.0
4     326.0
Name: total_bedrooms, dtype: float64

In [ ]:
# i want to read the 1st row of the total_bedrooms column
df['total_bedrooms'][7]

168.0

In [ ]:
#read the multiple columns at a time from above df
df[['total_rooms','total_bedrooms','population','households']].head()

   total_rooms  total_bedrooms  population  households
0       5612.0          1283.0      1015.0       472.0
1       7650.0          1901.0      1129.0       463.0
2        720.0           174.0       333.0       117.0
3       1501.0           337.0       515.0       226.0
4       1454.0           326.0       624.0       262.0

In [ ]:
#how can we access rows in middle of df
#--> by using Slicing,indexing and filtring

In [ ]:
#locating the rows
##use the df.loc
#df.loc[index]

df.loc[0]
#df.loc[start:end]
df.loc[5:2:-1]

# read the rows with even and odd position[start:stop:step]
df.loc[0:100:2].head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0

In [ ]:
#even positions characters  of particular column
df.loc[0::2,['total_bedrooms','population']].head(10)
# we cannot give more than one column name in the acessing of characters using slicing

    total_bedrooms  population
0           1283.0      1015.0
2            174.0       333.0
4            326.0       624.0
6            680.0      1841.0
8           1175.0      3134.0
10           801.0      2434.0
12           248.0       580.0
14           378.0       949.0
16           322.0       666.0
18           386.0       775.0

In [ ]:
df['total_bedrooms']%2==0  #to check even and odd valus in columns

0        False
1        False
2         True
3        False
4         True
         ...
16995     True
16996     True
16997    False
16998     True
16999     True
Name: total_bedrooms, Length: 17000, dtype: bool

In [ ]:
df_even=df[df['total_bedrooms']%2==0]['total_bedrooms']
df_even

2        174.0
4        326.0
5        236.0
6        680.0
7        168.0
         ...
16991    616.0
16995    394.0
16996    528.0
16998    552.0
16999    300.0
Name: total_bedrooms, Length: 8590, dtype: float64

In [ ]:
df.shape

(17000, 9)

**02-12-2024**

In [ ]:
import pandas as pd

In [ ]:
#iloc : pass axes numbers for index and columns
df=pd.read_csv("/content/sample_data/california_housing_train.csv")

In [ ]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [ ]:
#syntax : df.iloc['row_index','column_index']

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
#latitude housing_median_age total_rooms total_bedrooms and print 1st 3 rows
df.iloc[0:4,1:5]

   latitude  housing_median_age  total_rooms  total_bedrooms
0     34.19                15.0       5612.0          1283.0
1     34.40                19.0       7650.0          1901.0
2     33.69                17.0        720.0           174.0
3     33.64                14.0       1501.0           337.0

In [ ]:
df.iloc[1,3]

7650.0

In [ ]:
df.iloc[3,5]

515.0

In [ ]:
df['total_rooms'][1]

7650.0

In [ ]:
#what is the difference between loc and iloc
#loc support filtering and iloc doesn't support filtering
#how can apply in the loc and we cannot apply conditions in iloc
df.loc[0:3]#locating the rows
df.loc[df['total_rooms']%2==0].head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0

In [ ]:
df.iloc[df['total_rooms']%2==0].head()
#NotImplementedError: iLocation based boolean indexing on an integer type is not available

NotImplementedError: iLocation based boolean indexing on an integer type is not available

In [ ]:
#Remove and find the duplicates from df
df.duplicated().sum()

0

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
#how can we find the unique values?
df['households'].unique()

array([ 472.,  463.,  117., ..., 1392., 1475.,  992.])

In [ ]:
df['total_bedrooms'].value_counts()

total_bedrooms
280.0     48
309.0     44
331.0     43
394.0     43
345.0     43
          ..
2405.0     1
1797.0     1
1024.0     1
1494.0     1
936.0      1
Name: count, Length: 1848, dtype: int64

## SYNTAX'S

#df.head()
#df.tail()
#df.dtypes
#df.shape-->prints the rows and cols
#df.size--->print rows*cols
#df.columns
#df.info()---> print the overall information about df
#df.describe()---> describe the df in the mean of statastics
#df.isnull().sum()-->total number of null values
#df.fillna()--> fill the null values
#df.loc[]-->locates the rows
#df.iloc ---> locates elements
#df.duplicated()
#df.drop_duplicates()--->remove duplicates
#df[column_name].unique()--> prints list of uniques values
#df[column_name].value_counts()---> frequency of each element

In [ ]:
#How to apply filters on the dataset
#By using the apply()-->it takes an function as an argument and apply to eacj item in the data set
#df.apply(function,convert_dtype=True, arg())

In [ ]:
d={'name': ['a','b','c','d','e'],
   'marks':[56,70,40,80,90]
}
#convert above dictionary to data_frame
df=pd.DataFrame(d)
df

  name  marks
0    a     56
1    b     70
2    c     40
3    d     80
4    e     90

In [ ]:
#create a function o it can print pass or fail
def function(num):
  if num>=45:
    print("passs")
  else:
    print("fail")

In [ ]:
df['marks'].apply(function)
df['marks']

passs
passs
fail
passs
passs

0    56
1    70
2    40
3    80
4    90
Name: marks, dtype: int64

In [ ]:
#map() by using this method it transforms the values in series using the specific mapping data
data={'Grades':['A','B','C','D','E']
      }
#df=pd.DataFrame(data)
print(df.shape)
print(df)

(5, 2)
  name  marks
0    a     56
1    b     70
2    c     40
3    d     80
4    e     90

In [ ]:
grades={'A':'Excellent','B':'Good','C':'Fair','D':'Pass','E':'Fail'}
#syntax : new_sr=old.sr.map(mapping)
df['Grades']=df['Grades'].map(grades)
df

KeyError: 'Grades'

# Time series

In [ ]:
#what is time series data?
"""Time series data is a sequence of data points in cronological
order that is used by business to analyze the past data and make the future predictions"""
#weather forecast
#no of taxi rides in a month
#predicting a company stock price fo the next day

'Time series data is a sequence of data points in cronological\norder that is used by business to analyze the past data and make the future predictions'

In [ ]:
#components of time series
# it is consists of 4 components
# 1. Trend component :- This is a variation that moves up or down in a predictable pettern over long period
# 2. sesonality component :- The variation that is regular and periodic and repeats itself over a specific period is known as sesonality component
  #ex:- such as days,weeks, or the months,seasons
# 3. cyclic component :- is the variation that corresponds with business or economic, "boom-bust" cycles it follows their own pecular
# 4. random component :- irregular component

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#how can we generate a date range in pandas
#pd.date_range('start date',periods=,freq=)
rng=pd.date_range('1/1/2024',periods=200,freq='s')
rng

In [ ]:
ts=pd.Series(np.random.randint(0,200,len(rng)),index=rng)
ts.head()

In [ ]:
#sum the random numbers upto 2 min
ts.resample('2min').sum()

NameError: name 'ts' is not defined

# Pivot table

In [ ]:
df=pd.DataFrame(
    {
        "A":['one','one','two','three']*3,
        "B":["A","B","C"]*4,
        "C":['Food','Food','Starter','Drink','Icecream','pan']*2,
        "D":np.random.randint(0,12,size=12),
        "E":np.random.randint(0,12,size=12)
    }
)
df

        A  B         C   D   E
0     one  A      Food   1   4
1     one  B      Food   0   1
2     two  C   Starter  11  11
3   three  A     Drink   9   9
4     one  B  Icecream  10   5
5     one  C       pan   1   2
6     two  A      Food  10   2
7   three  B      Food   6   1
8     one  C   Starter   4   8
9     one  A     Drink   1   9
10    two  B  Icecream  11   7
11  three  C       pan  11  11

In [ ]:
#pd.pivot_table()
pd.pivot_table(df,values='D',index=['A','B'],columns=['C'])

# Group by

-- splitting

-- applying

--combining

In [ ]:
df=pd.DataFrame(
    {
        "A":['one','one','two','three']*3,
        "B":["A","B","C"]*4,
        "C":['Food','Food','Starter','Drink','Icecream','pan']*2,
        "D":np.random.randint(0,12,size=12),
        "E":np.random.randint(0,12,size=12)
    }
)
df

        A  B         C   D   E
0     one  A      Food  10   8
1     one  B      Food  10  11
2     two  C   Starter   1   8
3   three  A     Drink   8   7
4     one  B  Icecream   2   4
5     one  C       pan   1   8
6     two  A      Food  10   7
7   three  B      Food  11   0
8     one  C   Starter   4   0
9     one  A     Drink   8   9
10    two  B  Icecream   3   0
11  three  C       pan   6   0

In [ ]:
#group by function is applicable with the aggregate function
#min,max.sum,avg,count,median,var,std

In [ ]:
#print the sum of food and drink for "c" and "e"
df.groupby("C")[["D","E"]].std()

KeyError: 'C'

In [ ]:
df.describe()

            revenue       runtime  vote_average    vote_count
count  4.546000e+04  45203.000000  45460.000000  45460.000000
mean   1.120935e+07     94.128199      5.618207    109.897338
std    6.433225e+07     38.407810      1.924216    491.310374
min    0.000000e+00      0.000000      0.000000      0.000000
25%    0.000000e+00     85.000000      5.000000      3.000000
50%    0.000000e+00     95.000000      6.000000     10.000000
75%    0.000000e+00    107.000000      6.800000     34.000000
max    2.787965e+09   1256.000000     10.000000  14075.000000

In [ ]:
df.groupby(['A','C']).sum()

#Merging 2 dataframes

In [ ]:
left=pd.DataFrame({'key':['food','Food'],'Ival':[1,2]})
right=pd.DataFrame({'key':['food','Food'],'rval':[3,4]})
pd.merge(left,right,on="key")

In [ ]:
df

splitting

In [ ]:
pieces=[df[:4],df[4:9],df[9:]]
pieces

In [ ]:
#combine this data
pd.concat(pieces)

In [ ]:
https://www.plus2net.com/python/pandas-student.php              #apply all the commands with student data

# 05-12-2024

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#read file
#read the data
df = pd.read_csv("/content/movies_metadata (1).csv")

<ipython-input-88-0cef9fd1d026>:3: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/movies_metadata (1).csv")

In [ ]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

**'genres'**

In [ ]:
df['genres'].values[25]

"[{'id': 18, 'name': 'Drama'}]"

In [ ]:
df['genres'].unique()

array(["[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]",
       "[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]",
       "[{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]",
       ...,
       "[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name': 'Comedy'}, {'id': 28, 'name': 'Action'}, {'id': 10751, 'name': 'Family'}]",
       "[{'id': 28, 'name': 'Action'}, {'id': 9648, 'name': 'Mystery'}, {'id': 53, 'name': 'Thriller'}, {'id': 27, 'name': 'Horror'}]",
       "[{'id': 10751, 'name': 'Family'}, {'id': 16, 'name': 'Animation'}, {'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]"],
      dtype=object)

In [ ]:
import ast
ast.literal_eval(df['genres'].values[505])     #1hot encoding

In [ ]:
#create a column for each genre--> say 1 if the movie has genre,else put 0
a={1,2}
a

{1, 2}

In [ ]:
import pandas as pd

In [ ]:
#we are going to look at the data and find and put all the unique genres
unique=set()
for i in df['genres']:
  #print(i)
  gen_list=ast.literal_eval(i) #it converts from string to list to dictionary
  for j in gen_list:
    unique.add(j['name'])

NameError: name 'ast' is not defined

In [ ]:
print(len(unique))

0

In [ ]:
unique

set()

In [ ]:
import ast
rows = []
genres=list(unique)
for i in df['genres']:
  gen_list=ast.literal_eval(i)
  movie_genres=[x['name']for x in gen_list]
  row=[] #store 1s and 0s for one movie
  for j in genres:
    row.append(int(j in movie_genres)) #checking genres are present or not
    rows.append(row)

In [ ]:
print(rows)

[]

In [ ]:
movie_genres = ['action','adventure']
unique = ['action','adventure','family','horror']
row = []
for j in unique:
  row.append(int(j in movie_genres))
row

[1, 1, 0, 0]

In [ ]:
genre = pd.DataFrame(rows,columns = genres)

NameError: name 'rows' is not defined

In [ ]:
genre

NameError: name 'genre' is not defined

In [ ]:
genre.shape

NameError: name 'genre' is not defined

In [ ]:
df.shape

In [ ]:
df = pd.concat([df,genre],axis = 1)
df.shape

In [ ]:
df

In [ ]:
df=df.drop(columns=['genres'])
df

In [ ]:
df.shape

In [ ]:
df.tail()

In [ ]:
"""df=df.drop(columns=['belongs_to_collection'])
df"""

# HOMEPAGE

In [ ]:
df['homepage']

In [ ]:
df.isnull().sum()

In [ ]:
#calculate the percentage of this null values
df['homepage'].isnull().sum()*100/df.shape[0]

In [ ]:
df['homepage_present'] = (~df['homepage'].isnull())
df.head()

In [ ]:
df=df.drop(columns = ['homepage'])
df

In [ ]:
df.head()

In [ ]:
#id coluumn

df['id']

In [ ]:
len(df['id'].unique())

In [ ]:
#drop the duplicate
df = df.drop_duplicates(subset='id')

In [ ]:
df.shape

In [ ]:
#How to drop particular rows in pandas

df= df.drop([35587],inplace=True)